### ISSUE TITLE
header on read the docs page

### ISSUE THREAD

**Issue by ChrisJarka** [WycliffeAssociates/btt-recorder-docs#2]
@PurpleGuitar I cannot find, so therefore cannot fix, the translationRecorder Information tag on the home page of the readthedocs page.  Please help!
![Snag_b672f95](https://user-images.githubusercontent.com/9850185/67986089-a500bf80-fc00-11e9-9c4e-9bef3d34caba.png)

**Comment by PurpleGuitar** [comment]
@ChrisJarka , I edited the conf.py file, which contained some references to tR.  Once the site updates, please review and see if it looks better (or worse) now.

**Comment by ChrisJarka** [comment]
@PurpleGuitar  Yes you did fix it - but not quite. :)
![Snag_f5797de](https://user-images.githubusercontent.com/9850185/68035693-83ecad00-fc9a-11e9-936e-a182834a19ba.png)

**Comment by PurpleGuitar** [comment]
Oops!  Thanks.  I think I fixed it -- would you please check again?

**Comment by ChrisJarka** [comment]
Thank you @PurpleGuitar
